### ISSUE TITLE
c72 model connection failed 

### ISSUE THREAD

**Issue by Maher-N** [amorenew/uhf_c72_plugin#10]
First of all, thank you for your great job 

I have an issue with C72 Chainway model won't establish a connection  
i got uart = /dev/ttyMT3
[serialPort_Open] [2] : No such file or directory

you can check the error in attached image 

THANKS IN ADVANCE 

![PHOTO-2023-06-12-22-46-58](https://github.com/amorenew/uhf_c72_plugin/assets/51826897/5c4b17cf-948b-432b-b55c-542893f939f4)

**Comment by amorenew** [comment]
@Maher-N  If your Android is 11 or up could you try this library
https://pub.dev/packages/rfid_c72_plugin 
don't forgot to follow its setup steps

**Comment by Maher-N** [comment]
FINALY IT WORKS ,, THANK YOUU AMR !! 💪🏻
