### ISSUE TITLE
Problems running the example code

### ISSUE THREAD

**Issue by svenssf** [amorenew/uhf_c72_plugin#11]
Hi there, thank you for and excellent contribution. 

We have a brand new C72 from Chainway. I'm trying to make it work with our flutter project but I'm getting the following errors. If you have any ideas as to how I could troubleshoot or fix this that would be greatly appreciated:

I/_plugin_exampl(12537): Compiler allocated 4303KB to compile void android.view.ViewRootImpl.performTraversals()
I/DeviceAPI_DeviceCon(12537): getDeviceInfoFromFile configPath=/storage/emulated/0/PDAConfig.txt
D/DeviceAPI_DeviceCon(12537): cw.model2:
D/DeviceAPI_DeviceCon(12537): cw.model:mtk.6765.c72
D/DeviceAPI_DeviceCon(12537): 最终cw.model:mtk.6765.c72
I/DeviceAPI_DeviceCon(12537): model=C72,uartPath=/dev/ttyMT3,uartPath_Fingerprint=/dev/ttyMT0,uartPath_RFID=
I/DeviceAPI_DeviceCon(12537): getModel() model=C72
D/DeviceAPI(12537): UHF device = C72
D/DeviceAPI(12537): UHF_Init----------->DevIsOpen = 1
D/DeviceAPI(12537): UHF uart = /dev/ttyMT3
D/DeviceAPI_SerialPort(12537): [SerialPort_Open] [2]: No such file or directory
D/DeviceAPI(12537): UHF uhf_uart_fd = -1
I/DeviceAPI_UHF(12537): init() Uart = /dev/ttyMT3
E/DeviceAPI_UHF(12537): init() err UHFOpenAndConnect result:-1
E/DeviceAPI_UHF(12537): setFrequencyMode() err :-1
E/DeviceAPI_UHF(12537): setPower() err :-1
E/DeviceAPI_UHF(12537): startInventory() err :-1

**Comment by amorenew** [comment]
@svenssf Could you try the following plugin?
https://pub.dev/packages/rfid_c72_plugin

**Comment by svenssf** [comment]
This worked really well! Thank you so much! Have you based the plugin on the SDK that Chainway provides on this page: https://www.chainwayeurope.com/en/download? Are you planning on maintaining this library or do you recommend that we create our own plugin using the Java SDK form Chainway? Again, thank you, so much and any help or recommendation as to how we should go about providing support for the C72 to our clients using our Flutter based APP is greatly appreciated.

**Comment by amorenew** [comment]
@svenssf 
- My plugin does not support Android 11 yet but the given plugin does it
- Maintaining this library, no need for Maintenance currently 
- Recommendations:
1- Keep testing edge cases
2- Put an online logging tool Firebase analytics and crashlytics

I am currently searching for a new job [full-time, part-time, Freelancing] if your Company need an extra hand
