### ISSUE TITLE
my UHF_C72 Device not connecting can someone help me

### ISSUE THREAD

**Issue by abdulrehmananwar** [amorenew/uhf_c72_plugin#12]
i am using this source code and run the apk on my uhf_c72 device butt its not connecting  
![WhatsApp Image 2023-10-04 at 10 23 01_31c608f7](https://github.com/amorenew/uhf_c72_plugin/assets/62530396/78ef050f-bcd9-4468-80bb-d563dcc5865d)
![WhatsApp Image 2023-10-04 at 10 10 11_f77cc2f7](https://github.com/amorenew/uhf_c72_plugin/assets/62530396/3c02c0bb-cfc4-4854-a518-1b94d0419be5)

**Comment by amorenew** [comment]
@abdulrehmananwar Not all devices have the same hardware
try this plugin instead
android 11 support in Rfid C72 [https://github.com/Justin-roy/Rfid_c72_plugin

**Comment by abdulrehmananwar** [comment]
i have downloaded from above link and build apk from sample butt still its not responding. 
![WhatsApp Image 2023-10-06 at 10 25 06_9f155003](https://github.com/amorenew/uhf_c72_plugin/assets/62530396/51175c27-05db-4d2b-a98e-41a461569744)

**Comment by amorenew** [comment]
@abdulrehmananwar Did you got any error?

**Comment by abdulrehmananwar** [comment]
no it not respond any error. when i tap on above green buttons.

**Comment by abdulrehmananwar** [comment]
do i neeed any configration to turn on 
![WhatsApp Image 2023-10-03 at 20 04 54_8ca2f913](https://github.com/amorenew/uhf_c72_plugin/assets/62530396/e54da342-a4cf-4984-901c-5ae741779824)

**Comment by amorenew** [comment]
@abdulrehmananwar maybe a different hardware if my plugin and Justin-roy/Rfid_c72_plugin not working then you need to check the SDK from the Chinese provider and make a plugin for it

**Comment by abdulrehmananwar** [comment]
they provide us this sdk butt i dont know how to make plugin from this sdk can you please guide me
[C72 SDK.zip](https://github.com/amorenew/uhf_c72_plugin/files/12829520/C72.SDK.zip)

**Comment by amorenew** [comment]
@abdulrehmananwar 
It would be best if you read about making a native Flutter plugin

The steps I used to convert the Native SDK to the Plugin:

1- Make a helper class to separate the SDK logic into simple and clean functions
like read cards function, write data, etc

2- Map the helper to functions in the Java plugin 

3- Listeners I used channels and RXJava for publishing to the channel.

4- Map the Enum of states to the same dart enums if needed

so the most important step is cleaning the native code to one helper class like the following class
https://github.com/amorenew/uhf_c72_plugin/blob/master/android/src/main/java/com/amorenew/c72/uhf_plugin/helper/UHFHelper.java

**Comment by amorenew** [comment]
@abdulrehmananwar when you used *Justin-roy/Rfid_c72_plugin* plugin did you play with the working area?
Set Work area Area Values { "1", "2" 4", "8", "22", "50", "51", "52", "128"} await UhfPlugin.setWorkArea;

try each area maybe it is the issue

**Comment by abdulrehmananwar** [comment]
its working now Thanks

**Comment by omarsawalhah** [comment]
> its working now Thanks

@abdulrehmananwar What WorkArea worked for you? 
@amorenew What is the difference and how this affects the scanning operation?
Thanks all.

**Comment by amorenew** [comment]
@abdulrehmananwar @omarsawalhah 
Work Area is like a writing standards, each number is stand for USA, China, Europe, and other types which I don’t remember right now
It depend on the machine which you used to write the data on the card

**Comment by abdulrehmananwar** [comment]
there is a one issue its not making sound while scaning
