### ISSUE TITLE
Not able to Filter the tag data

### ISSUE THREAD

**Issue by 1nlife** [amorenew/uhf_c72_plugin#15]
Not able to read the tag with reserved memory -
There is function in Android APP 

/// <summary>
        /// Setup scanning filter.
        /// </summary>
        /// <param name="ptr">Filter start address</param>
        /// <param name="cnt">Filter data length</param>
        /// <param name="data">Filter data</param>
        /// <param name="save">Permanent</param>
        /// <returns>True is success, false is failed</returns>
        public bool SetFilter(int ptr, int cnt, string data, bool save)
        {

https://github.com/stuarthallows/chainway-c72-rfid-scan/blob/7a1ed20a2eb5dfce860ab4bab0401e5e447a7378/C72Scan/C72Scan/C72Scan.Android/Services/RfidService.cs#L63
Not able to understand how to pass the following parameter

PTR
Length
STart add
data

Can you please help with this

**Comment by amorenew** [comment]
My plugin doesn’t work for Android 11 so it is better to add the suggestion for the following plugin
https://pub.dev/packages/rfid_c72_plugin
