### ISSUE TITLE
Running example error

### ISSUE THREAD

**Issue by SilvesterLi** [amorenew/uhf_c72_plugin#4]
E/AndroidRuntime( 8161): java.lang.UnsatisfiedLinkError: dlopen failed: library "libDeviceAPI.so" not found
E/AndroidRuntime( 8161): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
E/AndroidRuntime( 8161): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
E/AndroidRuntime( 8161): 	at java.lang.System.loadLibrary(System.java:1664)
E/AndroidRuntime( 8161): 	at com.rscja.deviceapi.DeviceAPI.<clinit>(DeviceAPI.java:2292)
E/AndroidRuntime( 8161): 	at com.rscja.deviceapi.DeviceAPI.getInstance(Unknown Source:0)
E/AndroidRuntime( 8161): 	at com.rscja.deviceapi.RFIDWithUHFUART.getDeviceAPI(RFIDWithUHFUART.java:52)
E/AndroidRuntime( 8161): 	at com.rscja.deviceapi.RFIDWithUHFUART.init(RFIDWithUHFUART.java:92)
E/AndroidRuntime( 8161): 	at com.amorenew.c72.uhf_plugin.helper.UHFHelper.connect(UHFHelper.java:74)
E/AndroidRuntime( 8161): 	at com.amorenew.c72.uhf_plugin.UHFPlugin.handleMethods(UHFPlugin.java:204)

**Comment by Berkant35** [comment]
Hey did you solve this problem ?

**Comment by pokkeerr** [comment]
Hey did you solve this problem ?

**Comment by SilvesterLi** [comment]
> Hey did you solve this problem ?
I just saw the comment, sorry for that, it's been so long that I've already forgoten how I resolved it but I'm using my personal fork which should works. I've tested it 2 weeks ago
you may use my fork[ here](https://github.com/SilvesterLi/uhf_c72_plugin?organization=SilvesterLi&organization=SilvesterLi)

**Comment by pokkeerr** [comment]
thanks for the replay,

i get these errors: 

I/DeviceAPI_UHF(27306): init() Uart = /dev/ttyMT3
E/DeviceAPI_UHF(27306): init() err UHFOpenAndConnect result:-1
E/DeviceAPI_UHF(27306): setFrequencyMode() err :-1
E/DeviceAPI_UHF(27306): setPower() err :-1
E/DeviceAPI_UHF(27306): startInventory() err :-1

**Comment by SilvesterLi** [comment]
> thanks for the replay,
> 
> i get these errors:
> 
> I/DeviceAPI_UHF(27306): init() Uart = /dev/ttyMT3 E/DeviceAPI_UHF(27306): init() err UHFOpenAndConnect result:-1 E/DeviceAPI_UHF(27306): setFrequencyMode() err :-1 E/DeviceAPI_UHF(27306): setPower() err :-1 E/DeviceAPI_UHF(27306): startInventory() err :-1

this means connection to uhf device error, did you test it on uhf device?
You may try these:
1. try to use the test software of your uhf device, make sure your device is working fine. Or you may restart your uhf device and try again.
2. did you init the program?

here are some example:
`
@override
  void initState() {
    super.initState();
    initPlatformState();
  }

Future<void> initPlatformState() async {
    String? platformVersion;
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      platformVersion = await UhfC72Plugin.platformVersion;
    } on PlatformException {
      platformVersion = 'Failed to get platform version.';
    }
    UhfC72Plugin.connectedStatusStream
        .receiveBroadcastStream()
        .listen(updateIsConnected);
    UhfC72Plugin.tagsStatusStream.receiveBroadcastStream().listen(updateTags);
    await UhfC72Plugin.connect;
    await UhfC72Plugin.setWorkArea('2');
    // await UhfC72Plugin.
    await UhfC72Plugin.setPowerLevel(power);
    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      _platformVersion = platformVersion!;
    });
  }
  String power = '30';
  double _elevation = 3;
  String _platformVersion = 'Unknown';
  bool _isStarted = false;
  bool _isEmptyTags = false;
  bool _isConnected = false;

List<String> _data = [];

  void updateTags(dynamic result) async{
    await UhfC72Plugin.clearData;
    TagEpc.parseTags(result).forEach((element) {
      String epc = element.epc;
      if(!_data.contains(epc)){
        setState(() {
          _data.add(epc);
        });
        epc = epc.substring(4,epc.length);
        sendData(epc);
      }
    });
    await UhfC72Plugin.clearData;
  }

  void updateIsConnected(dynamic isConnected) {
    //setState(() {
    _isConnected = isConnected;
    //});
  }

 @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          elevation: 0,
          backgroundColor: theme.scaffoldBackgroundColor,
          leading: InkWell(
            onTap: () => Navigator.of(context).pop(),
            child: Icon(FeatherIcons.chevronLeft,color: Colors.black,),
          ),
          title: FxText.titleMedium("test page", fontWeight: 600),
        ),
        body: Center(
          child:Column(
            children: [
              Container(
                child: InkWell(
                  onTap: ()async{
                    if(isSearching == false){
                      setState(() {
                        searchButtonText = 'searching tags...';
                        searchButtonColor = theme.colorScheme.error;
                        isSearching = true;
                      });
                      await UhfC72Plugin.clearData;
                      await UhfC72Plugin.startContinuous;
                    }else{
                      setState(() {
                        searchButtonText = 'start inventory';
                        searchButtonColor = theme.colorScheme.primary;
                        isSearching = false;
                      });
                      await UhfC72Plugin.stop;
                    }
                  
                  },
                  child: AvatarGlow(
                    glowColor: Colors.blue,
                    endRadius: 90.0,
                    duration: Duration(milliseconds: 2000),
                    repeat: true,
                    showTwoGlows: true,
                    repeatPauseDuration: Duration(milliseconds: 100),
                    child: Material(     // Replace this child with your own
                      elevation: 8.0,
                      shape: CircleBorder(),
                      child: CircleAvatar(
                        backgroundColor: theme.primaryColor,
                        child: Text(searchButtonText),
                        radius: 40.0,
                      ),
                    ),
                  ),
                ),
              ),
             
            ],
          ),
        )
    );
  }


`

**Comment by pokkeerr** [comment]
@SilvesterLi I restarted the device and checked if the UHF worked in another application and it's working fine !!

but there is an error line said : "D/DeviceAPI_SerialPort(29097): [SerialPort_Open] [2]: No such file or directory"

and when searching for solution, I found some developers add the file "chainway.ketstore" 
and included it in the girdle.build,

is there a step like this I have to do it?

**Comment by SilvesterLi** [comment]
> @SilvesterLi I restarted the device and checked if the UHF worked in another application and it's working fine !!
> 
> but there is an error line said : "D/DeviceAPI_SerialPort(29097): [SerialPort_Open] [2]: No such file or directory"
> 
> and when searching for solution, I found some developers add the file "chainway.ketstore" and included it in the girdle.build,
> 
> is there a step like this I have to do it?

I don't think so because I've also tested the original push which is also fine on my chainway uhf device.
is your device made by chainway?
you may also try this library
`  uhf_c72_plugin_2: ^0.2.6`

**Comment by pokkeerr** [comment]
@SilvesterLi I tried all libraries for UHF non of them works with me !

you can see the logs:
D/DeviceAPI( 6492): UHF uart = /dev/ttyMT3
D/DeviceAPI_SerialPort( 6492): [SerialPort_Open] [2]: No such file or directory
D/DeviceAPI( 6492): UHF uhf_uart_fd = -1
I/DeviceAPI_UHF( 6492): init() Uart = /dev/ttyMT3

the device is c72 made by chainway.

and after init() I get these logs : 

E/DeviceAPI_UHF( 6492): init() err UHFOpenAndConnect result:-1
E/DeviceAPI_UHF( 6492): setFrequencyMode() err :-1
E/DeviceAPI_UHF( 6492): setPower() err :-1

**Comment by pokkeerr** [comment]
@amorenew what is the version I have to use ?

**Comment by amorenew** [comment]
@pokkeerr incompatible means you need a different library, Chinese makes different SDKs so use your native SDK to make a new plugin

**Comment by pokkeerr** [comment]
@amorenew Thanks for your time :)

**Comment by abdallahalhyari** [comment]
@amorenew  dear Mr.amorenew   I find this error ("E/DeviceAPI_UHF: init() err UHFOpenAndConnect result:-1") while running the demo app by android studio(NATIVE).
kindly check it and reply to me.

**Comment by abdallahalhyari** [comment]
same this problem 
https://github.com/amorenew/uhf_c72_plugin/issues/4#issuecomment-1236945435

**Comment by amorenew** [comment]
@abdallahalhyari It looks like a different .so files(c++) implementation to connect to the hardware
Chinese keep making new SDKs and hardware over the time
So you could take this plugin as a guideline to make your own suitable implementation for your hardware
